version: '3'
services:

  mongo_service:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - 'mongo:/data/db'
    logging:
      driver: none

  authentication:
    build:
      context: ./authentication
    ports:
      - "8001:8001"
    image: authentication:latest
    depends_on:
      - mongo_service
      - ${TRAINERS_NAME}
    environment:
      - MONGODB_URL=mongodb://mongo_service:27017/
      - AUTHENTICATION_URL=${AUTH_NAME}:${AUTH_PORT}
      - BATTLES_URL=${BATTLES_NAME}:${BATTLES_PORT}
      - GYM_URL=${GYM_NAME}:${GYM_PORT}
      - LOCATION_URL=${LOCATION_NAME}:${LOCATION_PORT}
      - MICROTRANSACTION_URL=${MICROTRANSACTIONS_NAME}:${MICROTRANSACTIONS_PORT}
      - NOTIFICATIONS_URL=${NOTIFICATIONS_NAME}:${NOTIFICATIONS_PORT}
      - STORE_URL=${STORE_NAME}:${STORE_PORT}
      - TRADES_URL=${TRADES_NAME}:${TRADES_PORT}
      - TRAINERS_URL=${TRAINERS_NAME}:${TRAINERS_PORT}
    command: sh -c "./dockerize ${WAIT_MONGO} ${WAIT_TRAINERS} ${DEFAULT_FLAGS} && ./executable"

  battles:
    build:
      context: ./battles
    ports:
      - "${BATTLES_PORT}:${BATTLES_PORT}"
    image: battles:latest
    depends_on:
      - mongo_service
      - ${TRAINERS_NAME}
      - ${NOTIFICATIONS_NAME}
    environment:
      - MONGODB_URL=mongodb://mongo_service:27017/
      - AUTHENTICATION_URL=${AUTH_NAME}:${AUTH_PORT}
      - BATTLES_URL=${BATTLES_NAME}:${BATTLES_PORT}
      - GYM_URL=${GYM_NAME}:${GYM_PORT}
      - LOCATION_URL=${LOCATION_NAME}:${LOCATION_PORT}
      - MICROTRANSACTION_URL=${MICROTRANSACTIONS_NAME}:${MICROTRANSACTIONS_PORT}
      - NOTIFICATIONS_URL=${NOTIFICATIONS_NAME}:${NOTIFICATIONS_PORT}
      - STORE_URL=${STORE_NAME}:${STORE_PORT}
      - TRADES_URL=${TRADES_NAME}:${TRADES_PORT}
      - TRAINERS_URL=${TRAINERS_NAME}:${TRAINERS_PORT}
    command: sh -c "./dockerize ${WAIT_MONGO} ${WAIT_TRAINERS} ${WAIT_NOTIFICATIONS} ${DEFAULT_FLAGS} && ./executable"

  gym:
    build:
      context: ./gym
    ports:
      - "${GYM_PORT}:${GYM_PORT}"
    image: gym:latest
    depends_on:
      - mongo_service
      - ${LOCATION_NAME}
      - ${TRAINERS_NAME}
    environment:
      - MONGODB_URL=mongodb://mongo_service:27017/
      - AUTHENTICATION_URL=${AUTH_NAME}:${AUTH_PORT}
      - BATTLES_URL=${BATTLES_NAME}:${BATTLES_PORT}
      - GYM_URL=${GYM_NAME}:${GYM_PORT}
      - LOCATION_URL=${LOCATION_NAME}:${LOCATION_PORT}
      - MICROTRANSACTION_URL=${MICROTRANSACTIONS_NAME}:${MICROTRANSACTIONS_PORT}
      - NOTIFICATIONS_URL=${NOTIFICATIONS_NAME}:${NOTIFICATIONS_PORT}
      - STORE_URL=${STORE_NAME}:${STORE_PORT}
      - TRADES_URL=${TRADES_NAME}:${TRADES_PORT}
      - TRAINERS_URL=${TRAINERS_NAME}:${TRAINERS_PORT}
    command: sh -c "./dockerize ${WAIT_MONGO} ${WAIT_TRAINERS} ${WAIT_LOCATION} ${DEFAULT_FLAGS} && ./executable"

  location:
    build:
      context: ./location
    ports:
      - "${LOCATION_PORT}:${LOCATION_PORT}"
    image: location:latest
    depends_on:
      - mongo_service
      - ${TRAINERS_NAME}
    environment:
      - MONGODB_URL=mongodb://mongo_service:27017/
      - AUTHENTICATION_URL=${AUTH_NAME}:${AUTH_PORT}
      - BATTLES_URL=${BATTLES_NAME}:${BATTLES_PORT}
      - GYM_URL=${GYM_NAME}:${GYM_PORT}
      - LOCATION_URL=${LOCATION_NAME}:${LOCATION_PORT}
      - MICROTRANSACTION_URL=${MICROTRANSACTIONS_NAME}:${MICROTRANSACTIONS_PORT}
      - NOTIFICATIONS_URL=${NOTIFICATIONS_NAME}:${NOTIFICATIONS_PORT}
      - STORE_URL=${STORE_NAME}:${STORE_PORT}
      - TRADES_URL=${TRADES_NAME}:${TRADES_PORT}
      - TRAINERS_URL=${TRAINERS_NAME}:${TRAINERS_PORT}
    command: sh -c "./dockerize ${WAIT_MONGO} ${WAIT_TRAINERS} ${DEFAULT_FLAGS} && ./executable"

  microtransactions:
    build:
      context: ./microtransactions
    ports:
      - "${MICROTRANSACTIONS_PORT}:${MICROTRANSACTIONS_PORT}"
    image: microtransactions:latest
    depends_on:
      - mongo_service
      - ${TRAINERS_NAME}
    environment:
      - MONGODB_URL=mongodb://mongo_service:27017/
      - AUTHENTICATION_URL=${AUTH_NAME}:${AUTH_PORT}
      - BATTLES_URL=${BATTLES_NAME}:${BATTLES_PORT}
      - GYM_URL=${GYM_NAME}:${GYM_PORT}
      - LOCATION_URL=${LOCATION_NAME}:${LOCATION_PORT}
      - MICROTRANSACTION_URL=${MICROTRANSACTIONS_NAME}:${MICROTRANSACTIONS_PORT}
      - NOTIFICATIONS_URL=${NOTIFICATIONS_NAME}:${NOTIFICATIONS_PORT}
      - STORE_URL=${STORE_NAME}:${STORE_PORT}
      - TRADES_URL=${TRADES_NAME}:${TRADES_PORT}
      - TRAINERS_URL=${TRAINERS_NAME}:${TRAINERS_PORT}
    command: sh -c "./dockerize ${WAIT_MONGO} ${WAIT_TRAINERS} ${DEFAULT_FLAGS} && ./executable"

  notifications:
    build:
      context: ./notifications
    ports:
      - "${NOTIFICATIONS_PORT}:${NOTIFICATIONS_PORT}"
    image: notifications:latest
    depends_on:
      - mongo_service
    environment:
      - MONGODB_URL=mongodb://mongo_service:27017/
      - AUTHENTICATION_URL=${AUTH_NAME}:${AUTH_PORT}
      - BATTLES_URL=${BATTLES_NAME}:${BATTLES_PORT}
      - GYM_URL=${GYM_NAME}:${GYM_PORT}
      - LOCATION_URL=${LOCATION_NAME}:${LOCATION_PORT}
      - MICROTRANSACTION_URL=${MICROTRANSACTIONS_NAME}:${MICROTRANSACTIONS_PORT}
      - NOTIFICATIONS_URL=${NOTIFICATIONS_NAME}:${NOTIFICATIONS_PORT}
      - STORE_URL=${STORE_NAME}:${STORE_PORT}
      - TRADES_URL=${TRADES_NAME}:${TRADES_PORT}
      - TRAINERS_URL=${TRAINERS_NAME}:${TRAINERS_PORT}
    command: sh -c "./dockerize ${WAIT_MONGO} ${DEFAULT_FLAGS} && ./executable"

  store:
    build:
      context: ./store
    ports:
      - "${STORE_PORT}:${STORE_PORT}"
    image: store:latest
    depends_on:
      - mongo_service
      - ${TRAINERS_NAME}
    environment:
      - MONGODB_URL=mongodb://mongo_service:27017/
      - AUTHENTICATION_URL=${AUTH_NAME}:${AUTH_PORT}
      - BATTLES_URL=${BATTLES_NAME}:${BATTLES_PORT}
      - GYM_URL=${GYM_NAME}:${GYM_PORT}
      - LOCATION_URL=${LOCATION_NAME}:${LOCATION_PORT}
      - MICROTRANSACTION_URL=${MICROTRANSACTIONS_NAME}:${MICROTRANSACTIONS_PORT}
      - NOTIFICATIONS_URL=${NOTIFICATIONS_NAME}:${NOTIFICATIONS_PORT}
      - STORE_URL=${STORE_NAME}:${STORE_PORT}
      - TRADES_URL=${TRADES_NAME}:${TRADES_PORT}
      - TRAINERS_URL=${TRAINERS_NAME}:${TRAINERS_PORT}
    command: sh -c "./dockerize ${WAIT_MONGO} ${WAIT_TRAINERS} ${DEFAULT_FLAGS} && ./executable"

  trades:
    build:
      context: ./trades
    ports:
      - "${TRADES_PORT}:${TRADES_PORT}"
    image: trades:latest
    depends_on:
      - mongo_service
      - ${NOTIFICATIONS_NAME}
      - ${TRAINERS_NAME}
    environment:
      - MONGODB_URL=mongodb://mongo_service:27017/
      - AUTHENTICATION_URL=${AUTH_NAME}:${AUTH_PORT}
      - BATTLES_URL=${BATTLES_NAME}:${BATTLES_PORT}
      - GYM_URL=${GYM_NAME}:${GYM_PORT}
      - LOCATION_URL=${LOCATION_NAME}:${LOCATION_PORT}
      - MICROTRANSACTION_URL=${MICROTRANSACTIONS_NAME}:${MICROTRANSACTIONS_PORT}
      - NOTIFICATIONS_URL=${NOTIFICATIONS_NAME}:${NOTIFICATIONS_PORT}
      - STORE_URL=${STORE_NAME}:${STORE_PORT}
      - TRADES_URL=${TRADES_NAME}:${TRADES_PORT}
      - TRAINERS_URL=${TRAINERS_NAME}:${TRAINERS_PORT}
    command: sh -c "./dockerize ${WAIT_MONGO} ${WAIT_TRAINERS} ${WAIT_NOTIFICATIONS} ${DEFAULT_FLAGS} && ./executable"

  trainers:
    build:
      context: ./trainers
    ports:
      - "${TRAINERS_PORT}:${TRAINERS_PORT}"
    image: trainers:latest
    depends_on:
      - mongo_service
    environment:
      - MONGODB_URL=mongodb://mongo_service:27017/
      - AUTHENTICATION_URL=${AUTH_NAME}:${AUTH_PORT}
      - BATTLES_URL=${BATTLES_NAME}:${BATTLES_PORT}
      - GYM_URL=${GYM_NAME}:${GYM_PORT}
      - LOCATION_URL=${LOCATION_NAME}:${LOCATION_PORT}
      - MICROTRANSACTION_URL=${MICROTRANSACTIONS_NAME}:${MICROTRANSACTIONS_PORT}
      - NOTIFICATIONS_URL=${NOTIFICATIONS_NAME}:${NOTIFICATIONS_PORT}
      - STORE_URL=${STORE_NAME}:${STORE_PORT}
      - TRADES_URL=${TRADES_NAME}:${TRADES_PORT}
      - TRAINERS_URL=${TRAINERS_NAME}:${TRAINERS_PORT}
    command: sh -c "./dockerize ${WAIT_MONGO} ${DEFAULT_FLAGS} && ./executable"

volumes:
  mongo: