version: '3'

networks:
  default:
    external:
      name: primary_net

services:
  authentication:
    image: authentication:latest
    ports:
      - "8001:8001"
    depends_on:
      - ${TRAINERS_NAME}
    volumes:
      - logs:/logs
    environment:
      - MONGODB_URL=${USERS_MONGODB_URL}
      - AUTHENTICATION_URL=${AUTH_NAME}:${AUTH_PORT}
      - BATTLES_URL=${BATTLES_NAME}:${BATTLES_PORT}
      - GYM_URL=${GYM_NAME}:${GYM_PORT}
      - LOCATION_URL=${LOCATION_NAME}:${LOCATION_PORT}
      - MICROTRANSACTION_URL=${MICROTRANSACTIONS_NAME}:${MICROTRANSACTIONS_PORT}
      - NOTIFICATIONS_URL=${NOTIFICATIONS_NAME}:${NOTIFICATIONS_PORT}
      - STORE_URL=${STORE_NAME}:${STORE_PORT}
      - TRADES_URL=${TRADES_NAME}:${TRADES_PORT}
      - TRAINERS_URL=${TRAINERS_NAME}:${TRAINERS_PORT}
    command: sh -c "./dockerize ${WAIT_TRAINERS} ${DEFAULT_FLAGS}; ./executable"

  battles:
    image: battles:latest
    ports:
      - "${BATTLES_PORT}:${BATTLES_PORT}"
    depends_on:
      - ${TRAINERS_NAME}
      - ${NOTIFICATIONS_NAME}
    volumes:
      - logs:/logs
    environment:
      - AUTHENTICATION_URL=${AUTH_NAME}:${AUTH_PORT}
      - BATTLES_URL=${BATTLES_NAME}:${BATTLES_PORT}
      - GYM_URL=${GYM_NAME}:${GYM_PORT}
      - LOCATION_URL=${LOCATION_NAME}:${LOCATION_PORT}
      - MICROTRANSACTION_URL=${MICROTRANSACTIONS_NAME}:${MICROTRANSACTIONS_PORT}
      - NOTIFICATIONS_URL=${NOTIFICATIONS_NAME}:${NOTIFICATIONS_PORT}
      - STORE_URL=${STORE_NAME}:${STORE_PORT}
      - TRADES_URL=${TRADES_NAME}:${TRADES_PORT}
      - TRAINERS_URL=${TRAINERS_NAME}:${TRAINERS_PORT}
    command: sh -c "./dockerize ${WAIT_TRAINERS} ${WAIT_NOTIFICATIONS} ${DEFAULT_FLAGS}; ./executable"

  gym:
    image: gym:latest
    ports:
      - "${GYM_PORT}:${GYM_PORT}"
    depends_on:
      - ${LOCATION_NAME}
      - ${TRAINERS_NAME}
    volumes:
      - logs:/logs
    environment:
      - AUTHENTICATION_URL=${AUTH_NAME}:${AUTH_PORT}
      - BATTLES_URL=${BATTLES_NAME}:${BATTLES_PORT}
      - GYM_URL=${GYM_NAME}:${GYM_PORT}
      - LOCATION_URL=${LOCATION_NAME}:${LOCATION_PORT}
      - MICROTRANSACTION_URL=${MICROTRANSACTIONS_NAME}:${MICROTRANSACTIONS_PORT}
      - NOTIFICATIONS_URL=${NOTIFICATIONS_NAME}:${NOTIFICATIONS_PORT}
      - STORE_URL=${STORE_NAME}:${STORE_PORT}
      - TRADES_URL=${TRADES_NAME}:${TRADES_PORT}
      - TRAINERS_URL=${TRAINERS_NAME}:${TRAINERS_PORT}
    command: sh -c "./dockerize ${WAIT_TRAINERS} ${WAIT_LOCATION} ${DEFAULT_FLAGS}; ./executable"

  location:
    image: location:latest
    depends_on:
      - ${TRAINERS_NAME}
    ports:
      - "${LOCATION_PORT}:${LOCATION_PORT}"
    volumes:
      - logs:/logs
    environment:
      - MONGODB_URL=${LOCATION_MONGODB_URL}
      - AUTHENTICATION_URL=${AUTH_NAME}:${AUTH_PORT}
      - BATTLES_URL=${BATTLES_NAME}:${BATTLES_PORT}
      - GYM_URL=${GYM_NAME}:${GYM_PORT}
      - LOCATION_URL=${LOCATION_NAME}:${LOCATION_PORT}
      - MICROTRANSACTION_URL=${MICROTRANSACTIONS_NAME}:${MICROTRANSACTIONS_PORT}
      - NOTIFICATIONS_URL=${NOTIFICATIONS_NAME}:${NOTIFICATIONS_PORT}
      - STORE_URL=${STORE_NAME}:${STORE_PORT}
      - TRADES_URL=${TRADES_NAME}:${TRADES_PORT}
      - TRAINERS_URL=${TRAINERS_NAME}:${TRAINERS_PORT}
    command: sh -c "./dockerize ${WAIT_TRAINERS} ${DEFAULT_FLAGS}; ./executable"

  microtransactions:
    image: microtransactions:latest
    ports:
      - "${MICROTRANSACTIONS_PORT}:${MICROTRANSACTIONS_PORT}"
    depends_on:
      - ${TRAINERS_NAME}
    volumes:
      - logs:/logs
    environment:
      - MONGODB_URL=${MICROTRANSACTIONS_MONGODB_URL}
      - AUTHENTICATION_URL=${AUTH_NAME}:${AUTH_PORT}
      - BATTLES_URL=${BATTLES_NAME}:${BATTLES_PORT}
      - GYM_URL=${GYM_NAME}:${GYM_PORT}
      - LOCATION_URL=${LOCATION_NAME}:${LOCATION_PORT}
      - MICROTRANSACTION_URL=${MICROTRANSACTIONS_NAME}:${MICROTRANSACTIONS_PORT}
      - NOTIFICATIONS_URL=${NOTIFICATIONS_NAME}:${NOTIFICATIONS_PORT}
      - STORE_URL=${STORE_NAME}:${STORE_PORT}
      - TRADES_URL=${TRADES_NAME}:${TRADES_PORT}
      - TRAINERS_URL=${TRAINERS_NAME}:${TRAINERS_PORT}
    command: sh -c "./dockerize ${WAIT_TRAINERS} ${DEFAULT_FLAGS}; ./executable"

  notifications:
    image: notifications:latest
    ports:
      - "${NOTIFICATIONS_PORT}:${NOTIFICATIONS_PORT}"
    volumes:
      - logs:/logs
    environment:
      - MONGODB_URL=${NOTIFICATIONS_MONGODB_URL}
      - AUTHENTICATION_URL=${AUTH_NAME}:${AUTH_PORT}
      - BATTLES_URL=${BATTLES_NAME}:${BATTLES_PORT}
      - GYM_URL=${GYM_NAME}:${GYM_PORT}
      - LOCATION_URL=${LOCATION_NAME}:${LOCATION_PORT}
      - MICROTRANSACTION_URL=${MICROTRANSACTIONS_NAME}:${MICROTRANSACTIONS_PORT}
      - NOTIFICATIONS_URL=${NOTIFICATIONS_NAME}:${NOTIFICATIONS_PORT}
      - STORE_URL=${STORE_NAME}:${STORE_PORT}
      - TRADES_URL=${TRADES_NAME}:${TRADES_PORT}
      - TRAINERS_URL=${TRAINERS_NAME}:${TRAINERS_PORT}
    command: sh -c "./executable"

  store:
    image: store:latest
    depends_on:
      - ${TRAINERS_NAME}
    ports:
      - "${STORE_PORT}:${STORE_PORT}"
    volumes:
      - logs:/logs
    environment:
      - AUTHENTICATION_URL=${AUTH_NAME}:${AUTH_PORT}
      - BATTLES_URL=${BATTLES_NAME}:${BATTLES_PORT}
      - GYM_URL=${GYM_NAME}:${GYM_PORT}
      - LOCATION_URL=${LOCATION_NAME}:${LOCATION_PORT}
      - MICROTRANSACTION_URL=${MICROTRANSACTIONS_NAME}:${MICROTRANSACTIONS_PORT}
      - NOTIFICATIONS_URL=${NOTIFICATIONS_NAME}:${NOTIFICATIONS_PORT}
      - STORE_URL=${STORE_NAME}:${STORE_PORT}
      - TRADES_URL=${TRADES_NAME}:${TRADES_PORT}
      - TRAINERS_URL=${TRAINERS_NAME}:${TRAINERS_PORT}
    command: sh -c "./dockerize ${WAIT_TRAINERS} ${DEFAULT_FLAGS}; ./executable"

  trades:
    image: trades:latest
    ports:
      - "${TRADES_PORT}:${TRADES_PORT}"
    depends_on:
      - ${NOTIFICATIONS_NAME}
      - ${TRAINERS_NAME}
    volumes:
      - logs:/logs
    environment:
      - AUTHENTICATION_URL=${AUTH_NAME}:${AUTH_PORT}
      - BATTLES_URL=${BATTLES_NAME}:${BATTLES_PORT}
      - GYM_URL=${GYM_NAME}:${GYM_PORT}
      - LOCATION_URL=${LOCATION_NAME}:${LOCATION_PORT}
      - MICROTRANSACTION_URL=${MICROTRANSACTIONS_NAME}:${MICROTRANSACTIONS_PORT}
      - NOTIFICATIONS_URL=${NOTIFICATIONS_NAME}:${NOTIFICATIONS_PORT}
      - STORE_URL=${STORE_NAME}:${STORE_PORT}
      - TRADES_URL=${TRADES_NAME}:${TRADES_PORT}
      - TRAINERS_URL=${TRAINERS_NAME}:${TRAINERS_PORT}
    command: sh -c "./dockerize ${WAIT_TRAINERS} ${WAIT_NOTIFICATIONS} ${DEFAULT_FLAGS}; ./executable"

  trainers:
    image: trainers:latest
    ports:
      - "${TRAINERS_PORT}:${TRAINERS_PORT}"
    volumes:
      - logs:/logs
    environment:
      - MONGODB_URL=${TRAINERS_MONGODB_URL}
      - AUTHENTICATION_URL=${AUTH_NAME}:${AUTH_PORT}
      - BATTLES_URL=${BATTLES_NAME}:${BATTLES_PORT}
      - GYM_URL=${GYM_NAME}:${GYM_PORT}
      - LOCATION_URL=${LOCATION_NAME}:${LOCATION_PORT}
      - MICROTRANSACTION_URL=${MICROTRANSACTIONS_NAME}:${MICROTRANSACTIONS_PORT}
      - NOTIFICATIONS_URL=${NOTIFICATIONS_NAME}:${NOTIFICATIONS_PORT}
      - STORE_URL=${STORE_NAME}:${STORE_PORT}
      - TRADES_URL=${TRADES_NAME}:${TRADES_PORT}
      - TRAINERS_URL=${TRAINERS_NAME}:${TRAINERS_PORT}
    command: sh -c "./executable"

volumes:
  logs: