apiVersion: v1
kind: Service
metadata:
  name: {{$.Values.global.services.gym.serviceNameHeadless}}
spec:
  clusterIP: None
  selector:
    app: {{$.Values.global.services.gym.name}}
  ports:
    - protocol: TCP
      port: {{$.Values.global.services.gym.port}}
      targetPort: {{$.Values.global.services.gym.port}}