apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{$.Values.global.services.gym.name}}
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: {{quote $.Values.global.services.gym.port}}
spec:
  serviceName: {{$.Values.global.services.gym.serviceNameHeadless}}
  selector:
    matchLabels:
      app: {{$.Values.global.services.gym.name}}
  replicas: {{$.Values.global.services.gym.n_replicas}}
  template:
    metadata:
      labels:
        app: {{$.Values.global.services.gym.name}}
    spec:
      containers:
        - name: {{$.Values.global.services.gym.name}}
          image: {{$.Values.global.services.gym.image}}
          command: ["sh", "-c", "./executable -l"]
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: {{$.Values.global.services.gym.port}}
          envFrom:
            - configMapRef:
                name: {{$.Values.global.api_configmap.name}}
          env:
            - name: MONGODB_URL
              value: "mongodb://{{$.Values.global.database.user}}:{{$.Values.global.database.mongodbRootPassword}}@{{$.Values.global.database.prefix}}-{{$.Values.global.services.gym.databaseName}}:{{$.Values.global.services.location.databasePort}}"
            - name: "HEADLESS_SERVICE_NAME"
              value: {{$.Values.global.services.gym.serviceNameHeadless}}
      nodeSelector:
        serversnode: "true"