apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{$.Values.global.services.notifications.name}}
spec:
  selector:
    matchLabels:
      app: {{$.Values.global.services.notifications.name}}
  replicas: {{$.Values.global.services.notifications.n_replicas}}
  serviceName: {{$.Values.global.services.notifications.serviceNameHeadless}}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: {{quote $.Values.global.services.notifications.port}}
      labels:
        app: {{$.Values.global.services.notifications.name}}
    spec:
      initContainers:
        - name: wait-trainers
          image: radial/busyboxplus:curl
          command: ['sh', '-c', "set -x; while [[ $(curl -sw '%{http_code}' 'trainers-service.default.svc.cluster.local:8009/trainers/status' -o /dev/null) -ne 200 ]]; do sleep 15; done"]
      containers:
        - name: {{$.Values.global.services.notifications.name}}
          image: {{$.Values.global.services.notifications.image}}
          imagePullPolicy: Never
          command: ["sh", "-c", "./executable -l -d"]
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: {{$.Values.global.services.notifications.port}}
          env:
            - name: MONGODB_URL
              value: "mongodb://{{$.Values.global.database.user}}:{{$.Values.global.database.mongodbRootPassword}}@{{$.Values.global.database.prefix}}-{{$.Values.global.services.notifications.databaseName}}:{{$.Values.global.services.notifications.databasePort}}"
            - name: "LOCATION"
              value: {{quote $.Values.global.location}}
            - name: KAFKA_URL
              value: "novapokemon-kafka:9092"
            - name: "NODE_NUM"
              value: {{quote $.Values.global.nodeNum}}
          envFrom:
            - configMapRef:
                name: {{$.Values.global.api_configmap.name}}
      nodeSelector:
        serversnode: "true"