apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$.Values.global.services.store.name}}
spec:
  selector:
    matchLabels:
      app: {{$.Values.global.services.store.name}}
  replicas: {{$.Values.global.services.store.n_replicas}}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: {{quote $.Values.global.services.store.port}}
      labels:
        app: {{$.Values.global.services.store.name}}
    spec:
      containers:
        - name: {{$.Values.global.services.store.name}}
          image: {{$.Values.global.services.store.image}}
          command: ["sh", "-c", "./executable -l"]
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: {{$.Values.global.services.store.port}}
          envFrom:
            - configMapRef:
                name: {{$.Values.global.api_configmap.name}}
      nodeSelector:
        serversnode: "true"