apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: novapokemon-prometheus-alertmanager
  namespace: default
  annotations:
    meta.helm.sh/release-name: novapokemon
    meta.helm.sh/release-namespace: default
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app: prometheus
    app.kubernetes.io/managed-by: Helm
    chart: prometheus-11.3.0
    component: server
    heritage: Helm
    release: novapokemon
spec:
  storageClassName: prometheus-pvc-server
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  volumeMode: Filesystem