apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server-pv
  labels:
    type: local
spec:
  storageClassName: prometheus-pvc-server
  capacity:
    storage: 10G
  claimRef:
    namespace: default
    name: "novapokemon-prometheus-server"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/logs_prometheusServer"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager-pv
  labels:
    type: local
spec:
  storageClassName: prometheus-pvc-alertmanager
  capacity:
    storage: 10G
  claimRef:
    namespace: default
    name: "novapokemon-prometheus-alertmanager"
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/logs_prometheusAlertManager"