apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{$.Values.global.services.microtransactions.name}}
spec:
  selector:
    matchLabels:
      app: {{$.Values.global.services.microtransactions.name}}
  replicas: {{$.Values.global.services.microtransactions.n_replicas}}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: {{quote $.Values.global.services.microtransactions.port}}
      labels:
        app: {{$.Values.global.services.microtransactions.name}}
    spec:
      containers:
        - name: {{$.Values.global.services.microtransactions.name}}
          image: {{$.Values.global.services.microtransactions.image}}
          command: ["sh", "-c", "./executable -l"]
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: {{$.Values.global.services.microtransactions.port}}
          env:
            - name: MONGODB_URL
              value: "mongodb://{{$.Values.global.database.user}}:{{$.Values.global.database.mongodbRootPassword}}@{{$.Values.global.database.prefix}}-{{$.Values.global.services.microtransactions.databaseName}}:{{$.Values.global.services.microtransactions.databasePort}}"
          envFrom:
            - configMapRef:
                name: {{$.Values.global.api_configmap.name}}
      nodeSelector:
        serversnode: "true"