apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: novapokemon-ingress
spec:
  rules:
    - http:
        paths:
          - path: /{{$.Values.global.services.auth.name}}
            pathType: Prefix
            backend:
              serviceName: {{$.Values.global.services.auth.serviceName}}
              servicePort: {{$.Values.global.services.auth.port}}

          - path: /{{$.Values.global.services.battles.name}}
            pathType: Prefix
            backend:
              serviceName: {{$.Values.global.services.battles.serviceName}}
              servicePort: {{$.Values.global.services.battles.port}}

          - path: /{{$.Values.global.services.location.name}}
            pathType: Prefix
            backend:
              serviceName: {{$.Values.global.services.location.serviceName}}
              servicePort: {{$.Values.global.services.location.port}}

          - path: /{{$.Values.global.services.gym.name}}
            pathType: Prefix
            backend:
              serviceName: {{$.Values.global.services.gym.serviceNameHeadless}}
              servicePort: {{$.Values.global.services.gym.port}}

          - path: /{{$.Values.global.services.notifications.name}}
            pathType: Prefix
            backend:
              serviceName: {{$.Values.global.services.notifications.serviceName}}
              servicePort: {{$.Values.global.services.notifications.port}}

          - path: /{{$.Values.global.services.microtransactions.name}}
            pathType: Prefix
            backend:
              serviceName: {{$.Values.global.services.microtransactions.serviceName}}
              servicePort: {{$.Values.global.services.microtransactions.port}}

          - path: /{{$.Values.global.services.store.name}}
            pathType: Prefix
            backend:
              serviceName: {{$.Values.global.services.store.serviceName}}
              servicePort: {{$.Values.global.services.store.port}}

          - path: /{{$.Values.global.services.trades.name}}
            pathType: Prefix
            backend:
              serviceName: {{$.Values.global.services.trades.serviceName}}
              servicePort: {{$.Values.global.services.trades.port}}

          - path: /{{$.Values.global.services.trainers.name}}
            pathType: Prefix
            backend:
              serviceName: {{$.Values.global.services.trainers.serviceName}}
              servicePort: {{$.Values.global.services.trainers.port}}

          - path: /kubernetes-dashboard
            pathType: Prefix
            backend:
              serviceName: kubernetes-dashboard
              servicePort: 443