apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: novapokemon-ingress
spec:
  rules:
    - http:
        paths:
          - path: /{{$.Values.global.services.trainers.name}}
            pathType: Prefix
            backend:
              serviceName: {{$.Values.global.services.trainers.serviceName}}
              servicePort: {{$.Values.global.services.trainers.port}}

          - path: /{{$.Values.global.services.auth.name}}
            pathType: Prefix
            backend:
              serviceName: {{$.Values.global.services.auth.serviceName}}
              servicePort: {{$.Values.global.services.auth.port}}