apiVersion: v1
kind: Service
metadata:
  name: {{$.Values.global.services.trainers.serviceNameHeadless}}
spec:
  selector:
    app: {{$.Values.global.services.trainers.name}}
  ports:
    - protocol: TCP
      port: {{$.Values.global.services.trainers.port}}
      targetPort: {{$.Values.global.services.trainers.port}}
  clusterIP: None