apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{$.Values.global.services.trainers.name}}
spec:
  selector:
    matchLabels:
      app: {{$.Values.global.services.trainers.name}}
  replicas: {{$.Values.global.services.trainers.n_replicas}}
  serviceName: {{$.Values.global.services.trainers.serviceNameHeadless}}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: {{quote $.Values.global.services.trainers.port}}
      labels:
        app: {{$.Values.global.services.trainers.name}}
    spec:
      initContainers:
        - name: wait-mongo
          image: novapokemon/wait-mongo:latest
          command: ['sh', '-c', "until mongostat -vvvvv --host=novapokemon-trainersdb --port=27017 --username=root --password=secretpassword --authenticationDatabase=admin -n 1 2>&1 | grep successfully ; do echo waiting for my db; sleep 2; done"]
      containers:
        - name: {{$.Values.global.services.trainers.name}}
          image: {{$.Values.global.services.trainers.image}}
          command: ["sh", "-c", "./executable -l"]
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: {{$.Values.global.services.trainers.port}}
          env:
            - name: MONGODB_URL
              value: "mongodb://{{$.Values.global.database.user}}:{{$.Values.global.database.mongodbRootPassword}}@{{$.Values.global.database.prefix}}-{{$.Values.global.services.trainers.databaseName}}:{{$.Values.global.services.trainers.databasePort}}"
          envFrom:
            - configMapRef:
                name: {{$.Values.global.api_configmap.name}}
      nodeSelector:
        serversnode: "true"