apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{$.Values.global.services.location.name}}-app
spec:
  selector:
    matchLabels:
      app: {{$.Values.global.services.location.name}}
  replicas: {{$.Values.global.services.location.n_replicas}}
  serviceName: {{$.Values.global.services.location.serviceName}}
  template:
    metadata:
      labels:
        app: {{$.Values.global.services.location.name}}
    spec:
      containers:
        - name: {{$.Values.global.services.location.name}}
          image: {{$.Values.global.services.location.image}}
          command: ["sh", "-c", "export SERVER_NUM=${HOSTNAME##*-}; ./executable -l"]
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: {{$.Values.global.services.location.port}}
          env:
            - name: MONGODB_URL
              value: "mongodb://{{$.Values.global.database.user}}:{{$.Values.global.database.mongodbRootPassword}}@{{$.Values.global.database.prefix}}-{{$.Values.global.services.location.databaseName}}:{{$.Values.global.services.location.databasePort}}"
          envFrom:
            - configMapRef:
                name: {{$.Values.global.api_configmap.name}}