apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{$.Values.global.services.location.name}}
spec:
  selector:
    matchLabels:
      app: {{$.Values.global.services.location.name}}
  replicas: {{$.Values.global.services.location.n_replicas}}
  serviceName: {{$.Values.global.services.location.serviceNameHeadless}}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: {{quote $.Values.global.services.location.port}}
      labels:
        app: {{$.Values.global.services.location.name}}
    spec:
      containers:
        - name: {{$.Values.global.services.location.name}}
          image: {{$.Values.global.services.location.image}}
          command: ["sh", "-c", "export SERVER_NUM=${HOSTNAME##*-}; ./executable -l"]
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: {{$.Values.global.services.location.port}}
          env:
            - name: MONGODB_URL
              value: "mongodb://{{$.Values.global.database.user}}:{{$.Values.global.database.mongodbRootPassword}}@{{$.Values.global.database.prefix}}-{{$.Values.global.services.location.databaseName}}:{{$.Values.global.services.location.databasePort}}"
            - name: "HEADLESS_SERVICE_NAME"
              value: {{$.Values.global.services.location.serviceNameHeadless}}
          envFrom:
            - configMapRef:
                name: {{$.Values.global.api_configmap.name}}
      initContainers:
        - name: init-location
          image: novapokemon/init-location:latest
          command: ['sh', '-c', "until mongostat -vvvvv --host=novapokemon-locationdb --port=27017 --username=root --password=secretpassword --authenticationDatabase=admin -n 1 2>&1 | grep successfully ; do echo waiting for my db; sleep 2; done"]
      nodeSelector:
        serversnode: "true"
