apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{$.Values.global.services.location.name}}
spec:
  selector:
    matchLabels:
      app: {{$.Values.global.services.location.name}}
  replicas: {{$.Values.global.services.location.n_replicas}}
  serviceName: {{$.Values.global.services.location.serviceNameHeadless}}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: {{quote $.Values.global.services.location.port}}
      labels:
        app: {{$.Values.global.services.location.name}}
    spec:
      containers:
        - name: {{$.Values.global.services.location.name}}
          image: {{$.Values.global.services.location.image}}
          imagePullPolicy: Never
          command: ["sh", "-c", "./executable -l -d"]
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: {{$.Values.global.services.location.port}}
          env:
            - name: MONGODB_URL
              value: "mongodb://{{$.Values.global.database.user}}:{{$.Values.global.database.mongodbRootPassword}}@{{$.Values.global.database.prefix}}-{{$.Values.global.services.location.databaseName}}:{{$.Values.global.services.location.databasePort}}"
            - name: "HEADLESS_SERVICE_NAME"
              value: {{$.Values.global.services.location.serviceNameHeadless}}
            - name: LOCATION
              value: {{$.Values.global.location}}
          envFrom:
            - configMapRef:
                name: {{$.Values.global.api_configmap.name}}
      initContainers:
        - name: wait-trainers
          image: radial/busyboxplus:curl
          command: ['sh', '-c', "set -x; while [[ $(curl -sw '%{http_code}' 'trainers-service.default.svc.cluster.local:8009/trainers/status' -o /dev/null) -ne 200 ]]; do sleep 15; done"]
        - name: wait-mongo
          image: novapokemon/wait-mongo:latest
          command: ['sh', '-c', "until mongostat -vvvvv --host=novapokemon-locationdb --port=27017 --username=root --password=secretpassword --authenticationDatabase=admin -n 1 2>&1 | grep successfully ; do echo waiting for my db; sleep 2; done"]
      nodeSelector:
        serversnode: "true"
