{
 "title": "Novapokemon - main",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Location Go routines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_namespace=\"default\", kubernetes_pod_name=~\"location.*\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Trades Go routines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_namespace=\"default\", kubernetes_pod_name=~\"trades.*\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Gym Go routines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_namespace=\"default\", kubernetes_pod_name=~\"gym.*\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Store Go routines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_namespace=\"default\", kubernetes_pod_name=~\"store.*\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Notifications Go routines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_namespace=\"default\", kubernetes_pod_name=~\"notification.*\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Battles Go routines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_namespace=\"default\", kubernetes_pod_name=~\"battles.*\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Microtransactions Go routines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_namespace=\"default\", kubernetes_pod_name=~\"microtransactions.*\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Trainers Go routines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{kubernetes_namespace=\"default\", kubernetes_pod_name=~\"trainers.*\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Connected clients to location servers",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "location_connected_clients",
     "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "Connected clients to notification servers",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 15 },
   "targets": [
    {
     "expr": "notifications_connected_clients",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Ongoing raids",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "gym_raids_started-gym_raids_finished",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Ongoing Battles",
   "type": "stat",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 15 },
   "targets": [
    {
     "expr": "battles_ongoing_battles",
     "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "rate notifications sent (1 min) - local",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 26 },
   "targets": [
    {
     "expr": "rate(notifications_sent_local[5m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Started raids",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 26 },
   "targets": [
    { "expr": "gym_raids_started", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Started Battles",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 26 },
   "targets": [
    {
     "expr": "battles_started",
     "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "rate notifications received (1 min) - kafka",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 30 },
   "targets": [
    {
     "expr": "rate(notifications_received_kafka[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Finished raids",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 30 },
   "targets": [
    { "expr": "gym_raids_finished", "legendFormat": "{{kubernetes_pod_name}}" }
   ]
  },
  {
   "title": "Finished Battles",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 30 },
   "targets": [
    {
     "expr": "battles_finished",
     "legendFormat": "{{statefulset_kubernetes_io_pod_name}}"
    }
   ]
  },
  {
   "title": "rate notifications sent (1 min) - kafka",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 34 },
   "targets": [
    {
     "expr": "rate(notifications_sent_kafka[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}