apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{$.Values.global.services.trades.name}}
spec:
  selector:
    matchLabels:
      app: {{$.Values.global.services.trades.name}}
  replicas: {{$.Values.global.services.trades.n_replicas}}
  serviceName: {{$.Values.global.services.trades.serviceNameHeadless}}
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: {{quote $.Values.global.services.trades.port}}
      labels:
        app: {{$.Values.global.services.trades.name}}
    spec:
      initContainers:
        - name: wait-trainers
          image: radial/busyboxplus:curl
          command: ['sh', '-c', "set -x; while [[ $(curl -sw '%{http_code}' 'trainers-service.default.svc.cluster.local:8009/trainers/status' -o /dev/null) -ne 200 ]]; do sleep 15; done"]
      containers:
        - name: {{$.Values.global.services.trades.name}}
          image: {{$.Values.global.services.trades.image}}
          command: ["sh", "-c", "./executable -l"]
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: {{$.Values.global.services.trades.port}}
          envFrom:
            - configMapRef:
                name: {{$.Values.global.api_configmap.name}}
          env:
            - name: "HEADLESS_SERVICE_NAME"
              value: {{$.Values.global.services.trades.serviceNameHeadless}}
      nodeSelector:
        serversnode: "true"