apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{$.Values.global.services.battles.name}}-app
spec:
  selector:
    matchLabels:
      app: {{$.Values.global.services.battles.name}}
  replicas: {{$.Values.global.services.battles.n_replicas}}
  serviceName: {{$.Values.global.services.battles.serviceNameHeadless}}
  template:
    metadata:
      labels:
        app: {{$.Values.global.services.battles.name}}
    spec:
      containers:
        - name: {{$.Values.global.services.battles.name}}
          image: {{$.Values.global.services.battles.image}}
          command: ["sh", "-c", "./executable -l"]
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          ports:
            - containerPort: {{$.Values.global.services.battles.port}}
          envFrom:
            - configMapRef:
                name: {{$.Values.global.api_configmap.name}}
          env:
            - name: "HEADLESS_SERVICE_NAME"
              value: {{$.Values.global.services.battles.serviceNameHeadless}}