apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubernetes.io/ingress-bandwidth: 15M
    kubernetes.io/egress-bandwidth: 15M
  name: iperf-server
  labels:
    app: iperf-server
spec:
  restartPolicy: OnFailure
  containers:
    - name: iperf-server
      image: networkstatic/iperf3
      command: [ "iperf3", "-s" ]
      ports:
        - containerPort: 5201
---
apiVersion: v1
kind: Service
metadata:
  name: iperf-server
  labels:
    app: iperf-server
spec:
  ports:
    - port: 5201
      targetPort: 5201
  selector:
    app: iperf-server