apiVersion: v2
name: deployment-chart
description: Helm chart for NOVAPokemon application
version: 0.1.0
appVersion: 1.16.0

dependencies:
  - name: mongodb-sharded
    version: ~1.3.1
    repository:  https://charts.bitnami.com/bitnami
    alias: trainersdb

  - name: mongodb-sharded
    version: ~1.3.1
    repository:  https://charts.bitnami.com/bitnami
    alias: usersdb

  - name: mongodb-sharded
    version: ~1.3.1
    repository:  https://charts.bitnami.com/bitnami
    alias: locationdb

  - name: mongodb-sharded
    version: ~1.3.1
    repository:  https://charts.bitnami.com/bitnami
    alias: microtransactionsdb

  - name: mongodb-sharded
    version: ~1.3.1
    repository:  https://charts.bitnami.com/bitnami
    alias: notificationsdb

  - name: mongodb-sharded
    version: ~1.3.1
    repository:  https://charts.bitnami.com/bitnami
    alias: gymsdb

  - name: elasticsearch
    version: 7.6.2
    repository: https://helm.elastic.co
    alias: elasticsearch-logging

  - name: kibana
    version: 7.6.2
    repository: https://helm.elastic.co
    alias: kibana

  - name: kafka
    version: 10.3.3
    repository: https://charts.bitnami.com/bitnami
    alias: kafka