dependencies:
  - name: mongodb-sharded
    version: ~1.3.1
    repository:  https://charts.bitnami.com/bitnami
    alias: trainersdb
  - name: mongodb-sharded
    version: ~1.3.1
    repository:  https://charts.bitnami.com/bitnami
    alias: usersdb

#  - name: mongodb-sharded
#    version: ~1.3.1
#    repository:  https://charts.bitnami.com/bitnami
#    alias: locationdb

#  - name: mongodb-sharded
#    version: ~1.3.1
#    repository:  https://charts.bitnami.com/bitnami
#    alias: microtransactionsdb

#  - name: mongodb-sharded
#    version: ~1.3.1
#    repository:  https://charts.bitnami.com/bitnami
#    alias: notificationsdb