dockerize_version: v0.6.1

## prefixes
dockerize:
  http_prefix: "http : //"
  tcp_prefix: "tcp : //"
  wait_flag: "-wait"
  wait_timeout_flag: "-timeout 60s"
  retry_interval_flag: "-wait-retry-interval 5s"
  default_flags: "$wait_timeout_flag $retry_interval_flag"

global:
  database:
    prefix: "novapokemon"
    user: "root"
    mongodbRootPassword: "secretpassword"
  services:
    trainers:
      image: novapokemon/trainers:latest
      name: "trainers"
      port: 8009
      n_replicas: 2
      serviceName: "trainers-service"
      databaseName: "trainersdb"
      databasePort: 27017

    auth:
      image: novapokemon/authentication:latest
      name: "authentication"
      port: 8001
      n_replicas: 2
      serviceName: "authentication-service"
      databaseName: "usersdb"
      databasePort: 27018

    battles:
      name: "battles"
      n_replicas: 2
      port: 8002

    gym:
      name: "gym"
      n_replicas: 2
      port: 8003

    location:
      name: "location"
      n_replicas: 1
      port: 8004

    microtransactions:
      name: "microtransactions"
      n_replicas: 2
      port: 8005

    notifications:
      name: "notifications"
      n_replicas: 2
      port: 8006

    store:
      name: "store"
      n_replicas: 2
      port: 8007

    trades:
      name: "trades"
      n_replicas: 2
      port: 8008

trainersdb:
  user: "root"
  mongodbRootPassword: "secretpassword"
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  shards: 1
  shardsvr:
    dataNode:
      replicas: 1
  mongos:
    replicas: 1
  configsvr:
    replicas: 1

usersdb:
  user: "root"
  service:
    port:
      27018
  mongodbRootPassword: "secretpassword"
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  shards: 1
  shardsvr:
    dataNode:
      replicas: 1
  mongos:
    replicas: 1
  configsvr:
    replicas: 1

microtransactionsdb:
  user: "root"
  mongodbRootPassword: "secretpassword"
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  shards: 1
  shardsvr:
    dataNode:
      replicas: 1
  mongos:
    replicas: 1
  configsvr:
    replicas: 1

locationdb:
  user: "root"
  mongodbRootPassword: "secretpassword"
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  shards: 1
  shardsvr:
    dataNode:
      replicas: 1
  mongos:
    replicas: 1
  configsvr:
    replicas: 1

notificationsdb:
  user: "root"
  mongodbRootPassword: "secretpassword"
  livenessProbe:
    enabled: false
  readinessProbe:
    enabled: false
  shards: 1
  shardsvr:
    dataNode:
      replicas: 1
  mongos:
    replicas: 1
  configsvr:
    replicas: 1

## hostnames
#auth_name: "authentication"
#battles_name: "battles"
#gym_name: "gym"
#location_name: "location"
#microtransactions_name: "microtransactions"
#notifications_name: "notifications"
#store_name: "store"
#trades_name: "trades"
#trainers_name: "trainers"
#

## wait flags
wait_auth: "$wait_flag $http_prefix$auth_name:$auth_port"
wait_battles: "$wait_flag $http_prefix$battles_name:$battles_port"
wait_gym: "$wait_flag $http_prefix$gym_name:$gym_port"
wait_location: "$wait_flag $http_prefix$location_name:$location_port"
wait_microtransactions: "$wait_flag $http_prefix$microtransactions_name:$microtransactions_port"
wait_notifications: "$wait_flag $http_prefix$notifications_name:$notifications_port"
wait_store: "$wait_flag $http_prefix$store_name:$store_port"
wait_trades: "$wait_flag $http_prefix$trades_name:$trades_port"
wait_trainers: "$wait_flag $http_prefix$trainers_name:$trainers_port"
#
#
#